### ISSUE TITLE
Packaging for Arch Linux

### ISSUE THREAD

**Issue by dvzrv** [subdownloader/subdownloader#25]
I'd like to further package subdownloader for Arch Linux.
Fedora already ships a version 2.0.19 somehow... I wonder what they use as source, but they point towards this repository as upstream!

Could you tag a new release? I'd be happy to update!

**Comment by dvzrv** [comment]
@madebr can you do anything about this?

**Comment by madebr** [comment]
Tagging of 2.0.19 was done by @sergiomb2 on his [personal repo](https://github.com/sergiomb2/subdownloader).
I guess the time has come to do a release, even though the cli version is in no way finished.

Anyway, I tagged [2.1.0-rc1](https://github.com/subdownloader/subdownloader/releases/tag/2.1.0-rc1).

Please test!

**Comment by sergiomb2** [comment]
@madebr  very sorry about my absent, I have to test upload ..., but  I have been completely busy , the app in general works , but navigation and things like that aren't good enough for me as I wrote somewhere in github , multi forlder and multi languages are not intuitive 

Version  2.0.19 is commit https://github.com/subdownloader/subdownloader/commits/2cb0ffb

with subdownloader-desktop.patch  [1] 

also I have 4 commit on top of if , may help you [2]

[1] https://src.fedoraproject.org/rpms/subdownloader/tree/master 
[2] https://github.com/sergiomb2/subdownloader/commits/master

**Comment by dvzrv** [comment]
@madebr the tests fail for me (using your -rc1 tag): 

```
running egg_info
writing SubDownloader.egg-info/PKG-INFO
writing dependency_links to SubDownloader.egg-info/dependency_links.txt
writing entry points to SubDownloader.egg-info/entry_points.txt
writing requirements to SubDownloader.egg-info/requires.txt
writing top-level names to SubDownloader.egg-info/top_level.txt
reading manifest file 'SubDownloader.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'subdownloader/languages/lm/*.lm'
warning: no files found matching 'subdownloader/client/gui/images.qrc'
warning: no files found matching 'subdownloader/client/gui/*.ui'
warning: no files found matching 'subdownloader/client/gui/Makefile'
warning: no files found matching '*.gif' under directory 'subdownloader/client/gui/images'
warning: no files found matching '*.ico' under directory 'subdownloader/client/gui/images'
warning: no files found matching '*.png' under directory 'subdownloader/client/gui/images'
warning: no files found matching '*.xpm' under directory 'subdownloader/client/gui/images'
writing manifest file 'SubDownloader.egg-info/SOURCES.txt'
running build_ext
main (unittest.loader._FailedTest) ... ERROR
filter (unittest.loader._FailedTest) ... ERROR
test_filepath (tests.test_videofile.TestVideofile) ... ERROR
test_metadata (tests.test_videofile.TestVideofile) ... ERROR
test_nonexisting (tests.test_videofile.TestVideofile) ... ERROR
test_osdb_hash (tests.test_videofile.TestVideofile) ... ERROR
test_size (tests.test_videofile.TestVideofile) ... ERROR
test_subtitles_initial (tests.test_videofile.TestVideofile) ... ERROR

======================================================================
ERROR: main (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: main
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/build/subdownloader/src/subdownloader-2.1.0_rc1/subdownloader/client/cli/main.py", line 10, in <module>
    from subdownloader.FileManagement import FileScan, Subtitle
ModuleNotFoundError: No module named 'subdownloader.FileManagement'


======================================================================
ERROR: filter (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: filter
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/build/subdownloader/src/subdownloader-2.1.0_rc1/subdownloader/client/cli/filter.py", line 6, in <module>
    from subdownloader.FileManagement import Subtitle
ModuleNotFoundError: No module named 'subdownloader.FileManagement'


======================================================================
ERROR: test_filepath (tests.test_videofile.TestVideofile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/subdownloader/src/subdownloader-2.1.0_rc1/tests/test_videofile.py", line 18, in setUp
    self.v = VideoFile(str(RESOURCE_AVI))
  File "/build/subdownloader/src/subdownloader-2.1.0_rc1/subdownloader/video2.py", line 52, in __init__
    if not self._filepath.exists():
AttributeError: 'str' object has no attribute 'exists'

======================================================================                    
ERROR: test_metadata (tests.test_videofile.TestVideofile)                                 
----------------------------------------------------------------------                              
Traceback (most recent call last):                        
  File "/build/subdownloader/src/subdownloader-2.1.0_rc1/tests/test_videofile.py", line 18, in setUp   
    self.v = VideoFile(str(RESOURCE_AVI))                                     
  File "/build/subdownloader/src/subdownloader-2.1.0_rc1/subdownloader/video2.py", line 52, in __init__
    if not self._filepath.exists():                         
AttributeError: 'str' object has no attribute 'exists'                    
                                                                                             
======================================================================                                                                                                                                   
ERROR: test_nonexisting (tests.test_videofile.TestVideofile)                                                                                                                        
----------------------------------------------------------------------                                                                                                                      
Traceback (most recent call last):                                                                                                                                                         
  File "/build/subdownloader/src/subdownloader-2.1.0_rc1/tests/test_videofile.py", line 18, in setUp                                                                                
    self.v = VideoFile(str(RESOURCE_AVI))                                                                                                                                                   
  File "/build/subdownloader/src/subdownloader-2.1.0_rc1/subdownloader/video2.py", line 52, in __init__
    if not self._filepath.exists():                                            
AttributeError: 'str' object has no attribute 'exists'                         
                                                                                                                   
======================================================================                                                                         
ERROR: test_osdb_hash (tests.test_videofile.TestVideofile)                                                          
----------------------------------------------------------------------                                      
Traceback (most recent call last):                                                                                 
  File "/build/subdownloader/src/subdownloader-2.1.0_rc1/tests/test_videofile.py", line 18, in setUp                                                                                    
    self.v = VideoFile(str(RESOURCE_AVI))                                                                                                      
  File "/build/subdownloader/src/subdownloader-2.1.0_rc1/subdownloader/video2.py", line 52, in __init__             
    if not self._filepath.exists():                                                                         
AttributeError: 'str' object has no attribute 'exists'                              
                                                                                                                                                                                                                                                                                                                                                                                   
======================================================================
ERROR: test_size (tests.test_videofile.TestVideofile)                         
----------------------------------------------------------------------                              
Traceback (most recent call last):                                                                               
  File "/build/subdownloader/src/subdownloader-2.1.0_rc1/tests/test_videofile.py", line 18, in setUp   
    self.v = VideoFile(str(RESOURCE_AVI))                           
  File "/build/subdownloader/src/subdownloader-2.1.0_rc1/subdownloader/video2.py", line 52, in __init__
    if not self._filepath.exists():                         
AttributeError: 'str' object has no attribute 'exists'                        
                                                                                         
======================================================================            
ERROR: test_subtitles_initial (tests.test_videofile.TestVideofile)                
----------------------------------------------------------------------                              
Traceback (most recent call last):                                            
  File "/build/subdownloader/src/subdownloader-2.1.0_rc1/tests/test_videofile.py", line 18, in setUp   
    self.v = VideoFile(str(RESOURCE_AVI))                                         
  File "/build/subdownloader/src/subdownloader-2.1.0_rc1/subdownloader/video2.py", line 52, in __init__
    if not self._filepath.exists():                                               
AttributeError: 'str' object has no attribute 'exists'                   
                                                                       
----------------------------------------------------------------------
Ran 8 tests in 2.337s

FAILED (errors=8)
Test failed: <unittest.runner.TextTestResult run=8 errors=8 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=8 errors=8 failures=0>
```

**Comment by madebr** [comment]
Will  fix them. Opened issue at #27

**Comment by dvzrv** [comment]
@madebr Awesome, thanks for the fast response!
Seems I have to package some more dependencies for subdownloader, before I can properly test it now...
I'll get back to you asap

**Comment by dvzrv** [comment]
Okay, I've now packaged the remaining things, that I need to continue (pymediainfo,langdetect).

However, there's still a test that fails:

```
running test
Searching for PyQt5>=5.0.0
Reading https://pypi.python.org/simple/PyQt5/
Downloading https://pypi.python.org/packages/e4/15/4e2e49f64884edbab6f833c6fd3add24d7938f2429aec1f2883e645d4d8f/PyQt5-5.10.1-5.10.1-cp35.cp36.cp37.cp38-abi3-manylinux1_x86_64.whl#md5=5a77e99718a65f2a1c8d59cd4fee5941
Best match: PyQt5 5.10.1
Processing PyQt5-5.10.1-5.10.1-cp35.cp36.cp37.cp38-abi3-manylinux1_x86_64.whl
Installing PyQt5-5.10.1-5.10.1-cp35.cp36.cp37.cp38-abi3-manylinux1_x86_64.whl to /build/subdownloader/src/subdownloader-2.1.0_rc2/.eggs
writing requirements to /build/subdownloader/src/subdownloader-2.1.0_rc2/.eggs/PyQt5-5.10.1-py3.6-linux-x86_64.egg/EGG-INFO/requires.txt

Installed /build/subdownloader/src/subdownloader-2.1.0_rc2/.eggs/PyQt5-5.10.1-py3.6-linux-x86_64.egg
Searching for sip<4.20,>=4.19.4
Reading https://pypi.python.org/simple/sip/
Downloading https://pypi.python.org/packages/8a/ea/d317ce5696dda4df7c156cd60447cda22833b38106c98250eae1451f03ec/sip-4.19.8-cp36-cp36m-manylinux1_x86_64.whl#md5=d428dece2fb2548a871399a4d2d33984
Best match: sip 4.19.8
Processing sip-4.19.8-cp36-cp36m-manylinux1_x86_64.whl
Installing sip-4.19.8-cp36-cp36m-manylinux1_x86_64.whl to /build/subdownloader/src/subdownloader-2.1.0_rc2/.eggs

Installed /build/subdownloader/src/subdownloader-2.1.0_rc2/.eggs/sip-4.19.8-py3.6-linux-x86_64.egg
running egg_info
writing SubDownloader.egg-info/PKG-INFO
writing dependency_links to SubDownloader.egg-info/dependency_links.txt
writing entry points to SubDownloader.egg-info/entry_points.txt
writing requirements to SubDownloader.egg-info/requires.txt
writing top-level names to SubDownloader.egg-info/top_level.txt
reading manifest file 'SubDownloader.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
/usr/lib/python3.6/site-packages/setuptools/dist.py:355: UserWarning: Normalizing '2.1.0-rc2' to '2.1.0rc2'
  normalized_version,
warning: no files found matching 'subdownloader/languages/lm/*.lm'
warning: no files found matching 'subdownloader/client/gui/images.qrc'
warning: no files found matching 'subdownloader/client/gui/*.ui'
warning: no files found matching 'subdownloader/client/gui/Makefile'
warning: no files found matching '*.gif' under directory 'subdownloader/client/gui/images'
warning: no files found matching '*.ico' under directory 'subdownloader/client/gui/images'
warning: no files found matching '*.png' under directory 'subdownloader/client/gui/images'
warning: no files found matching '*.xpm' under directory 'subdownloader/client/gui/images'
writing manifest file 'SubDownloader.egg-info/SOURCES.txt'
running build_ext
main (unittest.loader._FailedTest) ... ERROR
test_filepath (tests.test_videofile.TestVideofile) ... ok
test_folderpath (tests.test_videofile.TestVideofile) ... ok
test_metadata (tests.test_videofile.TestVideofile) ... ok
test_nonexisting (tests.test_videofile.TestVideofile) ... ok
test_osdb_hash (tests.test_videofile.TestVideofile) ... ok
test_size (tests.test_videofile.TestVideofile) ... ok
test_subtitles_initial (tests.test_videofile.TestVideofile) ... ok

======================================================================
ERROR: main (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: main
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/build/subdownloader/src/subdownloader-2.1.0_rc2/subdownloader/client/cli/main.py", line 10, in <module>
    from subdownloader.FileManagement import FileScan, Subtitle
ModuleNotFoundError: No module named 'subdownloader.FileManagement'


----------------------------------------------------------------------
Ran 8 tests in 3.460s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=8 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=8 errors=1 failures=0>

```

[Filemanagement](https://github.com/subdownloader/subdownloader/blob/master/subdownloader/client/cli/main.py#L10) doesn't seem to be around at all in the project?!

I'm also wondering about the download of PyQt5 (it is installed in the build environment, along with sip). Why is it not detected properly?

Another thing: CommonMark seems to be a requirement, too!

Also: Your travis script [only builds the sphinx docs](https://github.com/subdownloader/subdownloader/blob/master/.travis.yml#L16) and is therefore not representing the actual build status!

**Comment by madebr** [comment]
Hey,

- `subdownloader/client/cli/main.py` contained the old cli implementation. I removed it.
- I think your setup is downloading PyQt5 and sip because I have added a `requirements.txt` file in order to install the dependencies on travis (ecef4a17e7d7a742df044a42965bf5729520cb08). I needed this file to avoid the chicken and egg problem: `setup.py` also has dependencies.
- Travis is currently only installing the dependencies from pip, installing the current build, creating the man page and running the tests. `pip install .` will also execute some steps in the `setup.py` file (such as creating the `entry_points`). What do you understand under *actual build status*?
- About CommonMark. `CommonMark` is being downloaded as a dependency of `docutils`. See the output of travis. I just noticed that running `setup.py build_sphinx` will create an `.eggs` directory with `CommonMark` in it. I added it to the `.gitignore`

**Comment by dvzrv** [comment]
> What do you understand under actual build status?

If I run `setup.py build_sphinx` it doesn't build the whole project. Didn't think of the `pip install` part.

Hmm, I need to package sphinx-argparse as well then I guess, for the man page. Daemn.

If you have time, please, do release another -rc version! I'd be happy to do some further testing!

**Comment by madebr** [comment]
I tagged [2.1.0rc3](https://github.com/subdownloader/subdownloader/tree/2.1.0rc3). (I removed the hyphen)

**Comment by dvzrv** [comment]
@madebr Thanks! The tests run fine now!
Also: without the hyphen is actually better than with (because a release candidate version is then still considered a "lower version" than a "stable" release later, when comparing the versions - at least on Arch).

However, the tests folder is moved to `/usr/lib/python3.6/site-packages` when using

```
python setup.py install --skip-build \
     --optimize=1 \
     --prefix=/usr \
     --root="${pkgdir}"

```
They need to be excluded!

I'm still wondering about some things: Will the installation of the man page and desktop file be taken care of with setup.py as well?
And: Where are the [images](https://github.com/subdownloader/subdownloader/tree/master/scripts/gui/rc/images) expected to be located?
For xdg desktop file integration, there needs to be a subdownloader image somewhere below `/usr/share/pixmaps`.

**Comment by dvzrv** [comment]
Trying to start subdownloader now leads to:
```

Traceback (most recent call last):
  File "/usr/sbin/subdownloader", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3195, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3179, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3208, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 681, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 999, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 885, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'PyQt5>=5.0.0' distribution was not found and is required by SubDownloader


```

However, python-pyqt5 (5.10.1) is installed on my system, can be imported from the python shell and I can use it with another application (libffado's ffado-mixer).

Something seems fishy with the detection of the library.

**Comment by dvzrv** [comment]
If I remove the `PyQt5>=5.0.0` from `/usr/lib/python3.6/site-packages/SubDownloader-2.1.0rc3-py3.6.egg-info/requires.txt` subdownloader starts just fine.

**Comment by madebr** [comment]
- I'll exclude the `tests` directory in `setup.py`
- When installing subdownloader using pip, an entry point script is generated by `setuptools` that calls `SubDownloader`s main function. That script apparently checks whether all dependencies are installed but fails because PyQt5 is installed by the operating system package manager instead of the pip package manager. At least, this is the case on my Fedora distribution. This is ok for pip, but clashes with the os package manager I would suggest using (and renaming) the `subdownloader.py` in the root folder of the project. Unless you have another suggestion.
-

**Comment by madebr** [comment]
- The images and ui files in the `scripts` subfolder should not be packaged. They are compiled to python code by `scripts/gui/generate.py` to the files in `subdownloader/client/gui/generated/`.
- I would love to have all setup done in `setup.py` in one go:
  - (re)generating the files in `subdownloader/client/gui/generated/` folder,
  - creating the `man` file,
  - creating an appropriate entry point script,
  - ...

  Alas I do not know how..

**Comment by sergiomb2** [comment]
@dvzrv could you point me please where you got the your new PKGBUILD  ? [1] works [2] not found [3] don't see where is the link to PKGBUILD

[1]
https://aur.archlinux.org/packages/openvx/
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=openvx
[2]
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=subdownloader
[3]
https://www.archlinux.org/packages/community/any/subdownloader/ 


@madebr I will try look at setup.py , seems it is where I can be more useful and it is more priority 

Cheers

**Comment by dvzrv** [comment]
@sergiomb2 sorry, got busy with other things and forgot to push the package.
Will take a few minutes for svn2git to sync, but then the "Source Files" link should lead to the current version:
https://www.archlinux.org/packages/community-testing/any/subdownloader/

**Comment by dvzrv** [comment]
Any ETA on 2.1.0 release?
This builds and "works" for me so far.
Putting out a release (even if not feature complete) would probably be good to create some momentum for the project as well.
The code quality has improved A LOT already! :)

**Comment by dvzrv** [comment]
Any ETA on a non-RC release?

**Comment by dvzrv** [comment]
So, is this still happening? Would be great to finally move this package out of testing...

**Comment by sergiomb2** [comment]
Hello, I tested it yesterday , and in my point of view , still need some improvement in some usability of the app , so I don't think that it will be release soon.
