### ISSUE TITLE
crash when picking single file

### ISSUE THREAD

**Issue by glensc** [subdownloader/subdownloader#26]
### Description of problem

To find subtitles for single file, a crash happens.

### Steps to Reproduce

  1. Click "Select Videos"
  2. Crash with backtrace:

```
glen@rotten-fruit ~$ subdownloader 
Traceback (most recent call last):
  File "/usr/share/python3.6/site-packages/subdownloader/client/gui/searchFileWidget.py", line 303, in onButtonSearchSelectVideos
    self.search_videos(fileNames)
  File "/usr/share/python3.6/site-packages/subdownloader/client/gui/searchFileWidget.py", line 310, in search_videos
    self._search_videos_raw(paths)
  File "/usr/share/python3.6/site-packages/subdownloader/client/gui/searchFileWidget.py", line 323, in _search_videos_raw
    local_videos, local_subs = scan_videopaths(paths, callback=callback, recursive=True)
  File "/usr/share/python3.6/site-packages/subdownloader/filescan.py", line 24, in scan_videopaths
    videos, subtitles = scan_videopath(videopath, subcallback, recursive)
  File "/usr/share/python3.6/site-packages/subdownloader/filescan.py", line 40, in scan_videopath
    if not videopath.exists():
AttributeError: 'str' object has no attribute 'exists'
Aborted
```

### Version Info

  - SubDownloader Version: 2.0.19 df8427e
  - Python Version: 3.6.1
  - Operating System: PLD Linux

**Comment by madebr** [comment]
I believe this has been fixed in da9c9f46dc3dad9624186f64f3441cd8078d2b0f
Can you verify?

**Comment by glensc** [comment]
verified fixed
