### ISSUE TITLE
import _winreg

### ISSUE THREAD

**Issue by jackpoz** [subdownloader/subdownloader#29]
I got this error with a fresh install with Python 3.6.4

>subdownloader>subdownloader.py -g
Traceback (most recent call last):
  File "subdownloader\subdownloader.py", line 9, in <module>
    main()
  File "subdownloader\subdownloader\client\__main__.py", line 36, in main
    return_code = runner(options)
  File "subdownloader\subdownloader\client\gui\__init__.py", line 61, in run
    main_window = Main(None, "", options)
  File "subdownloader\subdownloader\client\gui\main.py", line 59, in __init__
    self.read_settings()
  File "subdownloader\subdownloader\client\gui\main.py", line 178, in read_settings
    self.initializeVideoPlayer(settings)
  File "subdownloader\subdownloader\client\gui\main.py", line 248, in initializeVideoPlayer
    import _winreg
ModuleNotFoundError: No module named '_winreg'

Renaming _winreg to winreg fixed it. I'm not experience with Python so no clue if I did some mistake during the install or if there is a missing package somewhere.

**Comment by madebr** [comment]
Hey,
`_winreg` has been renamed to `winreg` in Python3.
I've committed a fix 3b3773fe507cb21fd62b0ba00afcba65f515cca9.
To test it, you have to remove the settings file/registry settings of SubDownloader.

**Comment by jackpoz** [comment]
it works good now, thanks
