### ISSUE TITLE
ERROR: subdownloader.client.gui.imdbSearch # Error contacting OSDBServer.SearchMoviesOnIMDB NoneType: None

### ISSUE THREAD

**Issue by sergiomb2** [subdownloader/subdownloader#31]
### Description of problem
when try to find movie which I want upload , after click on find movie button of upload subtitles tab 

### Steps to Reproduce

  1.
  2.
  3.

### Version Info

  - SubDownloader Version:
  - Python Version:
  - Operating System:

**Comment by madebr** [comment]
I cannot reproduce this.

A connection error can be transient.
Does the program crash or does it recover (after reconnecting to the server)?

**Comment by sergiomb2** [comment]
OK 
meanwhile someone already upload the same subtitle so now I got [1] but subdownloader says "The upload failed." when IMHO should say "subtitle already uploaded" 

[1] 
[2018-06-17 03:35:03,405] DEBUG: subdownloader.provider.SDService # check_result(<data>)
[2018-06-17 03:35:03,405] DEBUG: subdownloader.provider.SDService # checking presence of "status" in result ...
[2018-06-17 03:35:03,405] DEBUG: subdownloader.provider.SDService # ... FOUND
[2018-06-17 03:35:03,406] DEBUG: subdownloader.provider.SDService # result["status"]="200 OK"
[2018-06-17 03:35:03,406] DEBUG: subdownloader.provider.SDService # applying regex to status ...
[2018-06-17 03:35:03,406] DEBUG: subdownloader.provider.SDService # ... regex SUCCEEDED
[2018-06-17 03:35:03,406] DEBUG: subdownloader.provider.SDService # Checking code=200 ...
[2018-06-17 03:35:03,406] DEBUG: subdownloader.provider.SDService # ... SUCCESS.
[2018-06-17 03:35:03,407] DEBUG: subdownloader.provider.SDService # check_result() finished (data is ok)

**Comment by sergiomb2** [comment]
when server fails to respond : 

```
[2018-06-17 03:27:10,848] WARNING: subdownloader.provider.SDService # data is None ==> FAIL
Traceback (most recent call last):
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/client/gui/uploadWidget.py", line 116, in on_upload_data_changed
    identificator.identify_videos(videos_to_identify)
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/provider/SDService.py", line 521, in identify_videos
    self.check_result(result)
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/provider/SDService.py", line 317, in check_result
    raise ProviderConnectionError(None, 'No message')
subdownloader.provider.SDService.ProviderConnectionError: code=None; reason=No message
```
```
Traceback (most recent call last):
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/client/gui/uploadWidget.py", line 116, in on_upload_data_changed
    identificator.identify_videos(videos_to_identify)
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/provider/SDService.py", line 520, in identify_videos
    result = self._safe_exec(run_query, None)
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/provider/SDService.py", line 357, in _safe_exec
    result = query()
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/provider/SDService.py", line 519, in run_query
    return self._xmlrpc_server.CheckMovieHash2(self._token, hashes)
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1167, in single_request
    resp = http_conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1321, in getresponse
    raise ResponseNotReady(self.__state)
http.client.ResponseNotReady: Request-sent
Aborted (core dumped)
```

**Comment by madebr** [comment]
Can you reproduce this on 2.1.0, branch-2.1.x, or current master? (I cant't)
