### ISSUE TITLE
All search results from files tab return error: argument 1 has unexpected type 'float'

### ISSUE THREAD

**Issue by jillian1701** [subdownloader/subdownloader#58]
### Description of problem
When using the 'search from video files' tab, no results are returned. Error log below

### How reproducible
Always

### Version Info

  - SubDownloader Version: 2.1.0
  - Python Version: Py3 - 3.10.12
  - Operating System: Ubuntu 22.04

### Additional info

Google would indicate this seems to be a common error with the result being: Incompatibility with Python 3.10+ due to implicit float-to-int conversion is no longer supported

Error log follow:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/subdownloader/client/gui/widgets/searchFileWidget.py", line 304, in onButtonSearchSelectVideos
    self.search_videos([Path(filename) for filename in fileNames])
  File "/usr/lib/python3/dist-packages/subdownloader/client/gui/widgets/searchFileWidget.py", line 311, in search_videos
    self._search_videos_raw(paths)
  File "/usr/lib/python3/dist-packages/subdownloader/client/gui/widgets/searchFileWidget.py", line 324, in _search_videos_raw
    local_videos, local_subs = scan_videopaths(paths, callback=callback, recursive=True)
  File "/usr/lib/python3/dist-packages/subdownloader/filescan.py", line 24, in scan_videopaths
    videos, subtitles = scan_videopath(videopath, subcallback, recursive)
  File "/usr/lib/python3/dist-packages/subdownloader/filescan.py", line 53, in scan_videopath
    return merge_path_subvideo(path_subvideos, callback)
  File "/usr/lib/python3/dist-packages/subdownloader/filescan.py", line 101, in merge_path_subvideo
    callback.update(vid_i)
  File "/usr/lib/python3/dist-packages/subdownloader/callback.py", line 69, in update
    self.on_update(value, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/subdownloader/callback.py", line 156, in on_update
    self._parent.update(parent_value, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/subdownloader/callback.py", line 69, in update
    self.on_update(value, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/subdownloader/client/gui/callback.py", line 82, in on_update
    self.status_progress.setValue(value)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'

**Comment by eric-saintetienne** [comment]
just type cast the value ` value`  to an int at the line indicated in the file. So something like ` int(value)`  instead of just ` value` .

That said now that opensubtitles API has been closed to VIP access only, this tool is not that useful (unless you've got a VIP pass)
